### ISSUE TITLE
totalIntensity is not defined

### ISSUE THREAD

**Issue by mal** [jeffbyrnes/hubot-forecast#5]
Looks like a missing `var` declaration?

```
[Forecast] Requesting forecast data: https://api.forecast.io/forecast/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/51.5211,-0.1413?units=us&exclude=hourly,daily,flags
[Sun Mar 01 2015 19:11:30 GMT+0000 (GMT)] ERROR ReferenceError: totalIntensity is not defined
  at handleContinuingWeather (./node_modules/hubot-forecast/src/forecast.coffee:176:9, <js>:121:11)
  at handleWeather (./node_modules/hubot-forecast/src/forecast.coffee:233:7, <js>:161:16)
  at handleJSON (./node_modules/hubot-forecast/src/forecast.coffee:253:11, <js>:177:20)
  at ./node_modules/hubot-forecast/src/forecast.coffee:269:9, <js>:193:18
  at IncomingMessage.<anonymous> (./node_modules/hubot/node_modules/scoped-http-client/src/index.js:80:22)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)
```

**Comment by jeffbyrnes** [comment]
@mal yeah, I've run into the same thing occasionally. Haven't had a chance to run it down yet. PRs are very welcome!
